name: Build Push Cleanup

on:
  push:
    branches:
      - master
    paths:
      - "image/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  image-build:
    strategy:
      matrix:
        include:
          - IMAGE_NAME: pttbbs
          - IMAGE_NAME: pttchrome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.IMAGE_NAME }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.IMAGE_NAME }}:buildcache,mode=max
          context: ./image/${{ matrix.IMAGE_NAME }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.IMAGE_NAME }}:${{ steps.date.outputs.date }}
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.IMAGE_NAME }}:latest

  cleanup:
    needs: image-build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Ghcr.io Cleanup
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: pttbbs,pttchrome
          delete-untagged: true
          keep-n-tagged: 5
